CREATE TABLE IF NOT EXISTS `mechants`(
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(64) NOT NULL DEFAULT '',
    `address` VARCHAR(128) NOT NULL DEFAULT '',
    `created_time` TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP,
    `updated_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);