CREATE TABLE IF NOT EXISTS `goods`(
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(128) NOT NULL DEFAULT '',
    `price` INT UNSIGNED NOT NULL DEFAULT 0,
    `unit` SMALLINT NOT NULL DEFAULT 0,
    `merchant_id` INT UNSIGNED NOT NULL DEFAULT 0,
    FOREIGN KEY (`merchant_id`) REFERENCES `mechants`(`id`),
    `created_time` TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP,
    `updated_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);